version: '3.8'

services:
  geekupstore-backend:
    image: vietducc/geekstore-backend:latest
    container_name: geekupstore-backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
